# Generated by Django 2.0.4 on 2018-04-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0005_auto_20180411_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='Favourites', to='Restaurante.Restaurant'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(related_name='Preferences', to='Restaurante.Keyword'),
        ),
    ]
