# Generated by Django 2.0.4 on 2018-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0006_auto_20180411_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.DateField(blank=True, null=True),
        ),
    ]
