# Generated by Django 2.0.4 on 2018-04-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0007_auto_20180411_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(related_name='Preferences', to='Restaurante.Keyword'),
        ),
    ]
