# Generated by Django 2.0.3 on 2018-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0011_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
