# Generated by Django 2.0.3 on 2018-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0012_profile_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artifial_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
