# Generated by Django 2.0.3 on 2018-04-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0013_profile_artifial_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='artifial_id',
            new_name='artificial_id',
        ),
    ]
