# Generated by Django 2.0.3 on 2018-05-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0014_auto_20180423_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artificial_id',
        ),
    ]
