# Generated by Django 2.0.4 on 2018-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0015_remove_profile_artificial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='Favourites', to='Restaurante.Restaurant'),
        ),
    ]
