# Generated by Django 2.0.4 on 2018-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0016_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='A unique title for this thing', null=True),
        ),
    ]
